version: '3'

services:
  backend:
    build: ./
    container_name: nestjs_api
    environment: 
      - PORT=3000
      - MONGO_PROD_CONNECTION_URI=mongodb://mongo_db:27017/holo-task
      - MONGO_TEST_CONNECTION_URI=mongodb://mongo_db:27017/holo-test
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks:
      - nestjs_network

  database:
    image: mongo
    container_name: mongo_db
    ports: 
      - "27017:27017"
    volumes:
      - "./mongo-backup:/data/db"
    networks:
      - nestjs_network

networks:
  nestjs_network:
    driver: bridge