name: Basic deploy
on:
  push:
    branches: [main]

jobs:
  EC2-Deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Docker tag
        id: set_tag
        run: echo "::set-output name=TAG_NAME::your-docker-image:${{ github.sha }}"

      - name: Build and compile
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ steps.set_tag.outputs.TAG_NAME }}

      - name: Deploy to EC2
        uses: omarbassuni2/holo-task@main
        with:
          aws_access_key_id: ${{ secrets.AWS_HOLO_ACCESS_KEY }}
          aws_secret_access_key: ${{ secrets.AWS_HOLO_SECRET_KEY }}
          aws_default_region: us-east-1
          dot_env: ${{ secrets.DOT_ENV }}
          image: ${{ steps.set_tag.outputs.TAG_NAME }}
